
url_list = [
        'https://www.youtube.com/c/%D0%9E%D0%BF%D1%8B%D1%82%D0%A5',
        "https://www.youtube.com/channel/UCB6Xe75HtqT4QSWauMSguRA",
        "https://www.youtube.com/c/AlexandraOrlova",
        "https://www.youtube.com/c/JUGru",
        "https://www.youtube.com/c/AlexChaplinsky",
        "https://www.youtube.com/c/A4a4a4a4",
        "https://www.youtube.com/c/%D0%91%D1%83%D0%BA%D0%B8%D1%87",
        "https://www.youtube.com/channel/UC6sWALQ1Z2wBM-VwkxNWlIQ",
        "https://www.youtube.com/c/Fireship",
        "https://www.youtube.com/c/%C3%95ZE%C3%91xo",
        "https://www.youtube.com/channel/UCdxuLSZrpklu1zLAStvfEjg",
        "https://www.youtube.com/c/%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC%D0%A7%D0%B5%D1%80%D0%BD%D0%BE%D0%B2",
        "https://www.youtube.com/c/JUZENTERTAINMENTOFFICIAL"
        # "https://www.youtube.com/c/BlackBeatsMusic",
        # "https://www.youtube.com/channel/UCZFbApVFCud7joZu7j8A9bA",
        # "https://www.youtube.com/c/AntonSaburov",
        # "https://www.youtube.com/c/lilyannexo",
        # "https://www.youtube.com/c/lilyannexo",
        # "https://www.youtube.com/c/BakrMusic",
        # "https://www.youtube.com/user/UNITEChillstep",
        # "https://www.youtube.com/c/FutureHouseHD",
        # "https://www.youtube.com/c/SuprunAlexey",
        # "https://www.youtube.com/c/ITKAMASUTRA",
        # "https://www.youtube.com/c/JomaOppa",
        # "https://www.youtube.com/c/NetworkChuck",
        # "https://www.youtube.com/c/DavidBombal",
        # "https://www.youtube.com/c/TesKill",
        # "https://www.youtube.com/c/cs50",
        # "https://www.youtube.com/c/KovalevskyiAcademy",
        # "https://www.youtube.com/c/ANDERGROUND",
        # "https://www.youtube.com/c/Qalamanimation",
        # "https://www.youtube.com/c/ArmaniKazakhHL",
        # "https://www.youtube.com/channel/UCbDMaUm8uT2NNMfgHUf0M-w",
        # "https://www.youtube.com/channel/UCPLe--8DDSWOlRz0AQ7879Q",
        # "https://www.youtube.com/c/ChilledSad",
        # "https://www.youtube.com/c/ChilledSad",
        # "https://www.youtube.com/c/NurlanQalamov",
        # "https://www.youtube.com/channel/UCY7nQDoFIwyP7NuyoDAvqsw",
        # "https://www.youtube.com/c/AJIuKZ2",
        # "https://www.youtube.com/c/AJIuKZ",
        # "https://www.youtube.com/channel/UCdzgn-YQ-1qdd9iV1GKHn1w",
        # "https://www.youtube.com/c/%D0%94%D0%B5%D0%BD%D1%8C%D0%B3%D0%B8%D0%95%D1%81%D1%82%D1%8C",
        # "https://www.youtube.com/c/kakbudto",
        # "https://www.youtube.com/c/gosha_dudar",
        # "https://www.youtube.com/channel/UCs5RbiUZXrTyrn5vyCeW8uQ",
        # "https://www.youtube.com/channel/UCmAdTZBOZqq5C9KAWTV94SQ",
        # "https://www.youtube.com/channel/UCsH5FYc8oHPi2cI3bcSC-JQ",
        # "https://www.youtube.com/c/Guitarkz",
        # "https://www.youtube.com/channel/UClQkK0aH9A6CWp2nqiiY_tw",
        # "https://www.youtube.com/c/Cgmeetup",
        # "https://www.youtube.com/c/bhadbhabie",
        # "https://www.youtube.com/channel/UCvvVOIyaYu2l4jiH9L8_eRw",
        # "https://www.youtube.com/c/musicianshut",
        # "https://www.youtube.com/channel/UCvgWu2Eet3IRR8NtypMG6WA",
        # "https://www.youtube.com/c/SerenaArt",
        # "https://www.youtube.com/c/postnauka",
        # "https://www.youtube.com/channel/UCQV5sw7uqJr67ZsNJ3D6E6Q",
        # "https://www.youtube.com/c/admeru",
        # "https://www.youtube.com/c/%D0%9F%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%B5%D0%9C%D1%8B%D1%81%D0%BB%D0%B8",
        # "https://www.youtube.com/c/%D0%A2%D0%95%D0%94%D0%BD%D0%B0%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC",
        # "https://www.youtube.com/c/KhanAcademyRussian",
        # "https://www.youtube.com/c/TutorOnlineRu12",
        # "https://www.youtube.com/c/beardbrand",
        # "https://www.youtube.com/c/NeBLOGER156",
        # "https://www.youtube.com/channel/UCVQmzlGDZPK8ku34ObSta0g",
        # "https://www.youtube.com/channel/UCVQmzlGDZPK8ku34ObSta0g",
        # "https://www.youtube.com/channel/UCxKm2eU4tJfy6Yrn1fuBqBw",
        # "https://www.youtube.com/c/AKSUNKAR",
        # "https://www.youtube.com/c/Meskalito",
        # "https://www.youtube.com/channel/UCALrBpcibaJzI8BJ8I9cqfw",
        # "https://www.youtube.com/c/%D0%A2%D0%B0%D1%80%D0%B8%D1%85%D0%9C%D0%B0%D1%80%D0%B8%D1%85",
        # "https://www.youtube.com/c/DDRECORDSKZ",
        # "https://www.youtube.com/channel/UC_wxi9eJkJ-s16X6E7E7jcQ",
        # "https://www.youtube.com/channel/UCYybbQ4rgbM27hF-Q5WbspQ",
        # "https://www.youtube.com/user/SAREC93",
        # "https://www.youtube.com/c/%D0%9C%D0%A3%D0%9B%D0%AC%D0%A2%D0%98%D0%A5%D0%90%D0%99%D0%9F",
        # "https://www.youtube.com/channel/UCmDPy8LmXKWDpWaizmZf90A",
        # "https://www.youtube.com/channel/UCmDPy8LmXKWDpWaizmZf90A",
        # "https://www.youtube.com/channel/UCy3iVGkgTXEIE3oprDr_lyw",
        # "https://www.youtube.com/channel/UCy3iVGkgTXEIE3oprDr_lyw"

]
